import type { Metadata } from 'next'
import { StackProvider, StackTheme } from '@stackframe/stack'
import { Inter } from 'next/font/google'
import './globals.css'
import Head from 'next/head'
import Header from '@/ui/Header/Header'
import React from 'react'
import { ToastContainer } from 'react-toastify'
import { connectToMongoDB } from '@/lib/db'
import 'react-toastify/dist/ReactToastify.css'
import { AuthProvider } from '@/contexts/AuthContext'
import { stackServerApp } from '@/stack'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'The Muse',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  connectToMongoDB()
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <StackProvider app={stackServerApp}>
            <StackTheme>
              <Head>
                <link
                  rel="stylesheet"
                  href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap"
                />
              </Head>
              <Header />
              {children}
              <ToastContainer />
            </StackTheme>
          </StackProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
